import static org.junit.jupiter.api.Assertions.assertEquals
import static org.junit.jupiter.api.Assertions.fail

private int tryEndCount = 0
private int catchCount = 0
private int finallyCount = 0

tryFinally(1)
assertEquals(1, tryEndCount, "try end")
assertEquals(0, catchCount, "catch")
assertEquals(1, finallyCount, "finally")

try {
  tryFinally(0)
  fail("Should have thrown exception")
} catch (ArithmeticException e) {
  assertEquals(0, tryEndCount, "try end")
  assertEquals(0, catchCount, "catch")
  assertEquals(1, finallyCount, "finally")
}
assertEquals(0, tryEndCount, "try end")
assertEquals(0, catchCount, "catch")
assertEquals(1, finallyCount, "finally")

fun void tryFinally(int a) {
  init()
  try {
    int result = 100 / a
    tryEndCount++
  } finally {
    finallyCount++
  }
}

tryCatchFinally(1)
assertEquals(1, tryEndCount, "try end")
assertEquals(0, catchCount, "catch")
assertEquals(1, finallyCount, "finally")

tryCatchFinally(0)
assertEquals(0, tryEndCount, "try end")
assertEquals(1, catchCount, "catch")
assertEquals(1, finallyCount, "finally")

fun void tryCatchFinally(int a) {
  init()
  try {
    int result = 100 / a
    tryEndCount++
  } catch (Exception e) {
    catchCount++
  } finally {
    finallyCount++
  }
}

assertEquals(0, returningTryCatchFinally(1))
assertEquals(1, tryEndCount, "try end")
assertEquals(0, catchCount, "catch")
assertEquals(1, finallyCount, "finally")

assertEquals(1, returningTryCatchFinally(0))
assertEquals(0, tryEndCount, "try end")
assertEquals(1, catchCount, "catch")
assertEquals(1, finallyCount, "finally")

fun int returningTryCatchFinally(int a) {
  init()
  try {
    int result = 100 / a
    tryEndCount++
    return 0
  } catch (Exception e) {
    catchCount++
    return 1
  } finally {
    finallyCount++
  }
}

assertEquals(0, returningTryFinally(1))
assertEquals(1, tryEndCount, "try end")
assertEquals(0, catchCount, "catch")
assertEquals(1, finallyCount, "finally")

try {
  returningTryFinally(0)
  fail("Should have thrown exception")
} catch (ArithmeticException e) {
    assertEquals(0, tryEndCount, "try end")
    assertEquals(0, catchCount, "catch")
    assertEquals(1, finallyCount, "finally")
}

fun int returningTryFinally(int a) {
  init()
  try {
    int result = 100 / a
    tryEndCount++
    return 0
  } finally {
    finallyCount++
  }
}

tryCatch(1)
assertEquals(1, tryEndCount, "try end")
assertEquals(0, catchCount, "catch")
assertEquals(0, finallyCount, "finally")

tryCatch(0)
assertEquals(0, tryEndCount, "try end")
assertEquals(1, catchCount, "catch")
assertEquals(0, finallyCount, "finally")

fun void tryCatch(int a) {
  init()
  try {
    int result = 100 / a
    tryEndCount++
  } catch (Exception e) {
    catchCount++
  }
}

assertEquals(0, returningTryCatch(1))
assertEquals(1, tryEndCount, "try end")
assertEquals(0, catchCount, "catch")
assertEquals(0, finallyCount, "finally")

assertEquals(1, returningTryCatch(0))
assertEquals(0, tryEndCount, "try end")
assertEquals(1, catchCount, "catch")
assertEquals(0, finallyCount, "finally")

fun int returningTryCatch(int a) {
  init()
  try {
    int result = 100 / a
    tryEndCount++
    return 0
  } catch (Exception e) {
    catchCount++
    return 1
  }
}


fun void init() {
  tryEndCount = 0
  catchCount = 0
  finallyCount = 0
}
